In [3]:
import numpy

mi_matriz_bien_bonis = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print('mi matriz bn bonis =')
print(mi_matriz_bien_bonis)

mi matriz bn bonis =
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
def rebanale_pimera_ultima(cualquier_matriz):
    return cualquier_matriz[:,[0,-1]]

In [7]:
rebanale_pimera_ultima(mi_matriz_bien_bonis)

array([[1, 3],
       [4, 6],
       [7, 9]])